#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  application:
#    name: glycemia-service

spring:
#  config:
#    import: optional:configserver:http://localhost:8888

  application:
    name: glycemia-service
    
server:
  port : 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost