server:
  port: 8089

#spring:
#  application:
#    name: api-gateway # Gateway service name
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true # Enables service discovery routing
#      routes: # Custom routes (optional, for fine-grained control)
#        - id: glycemic-route
#          uri: lb://GLYCEMIA-SERVICE
#          predicates:
#            - Path=/api/glycemic/**
#        - id: user-route
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/user/**