server:
  port: 8089

spring:
 cloud:
   gateway:
     routes:
       - id: glycemia-service
         uri: lb://GLYCEMIA-SERVICE
         predicates:
           - Path=/glycemia/**
         filters:
           - AuthenticationFilter


       - id: user-service
         uri: lb://USER-SERVICE
         predicates:
           - Path=/user/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**