spring:
#  config:
#    import: optional:configserver:http://localhost:8888

  application:
    name: user-service
    
server:
  port : 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost